extends:
  - plugin:astro/recommended
  - plugin:@typescript-eslint/recommended
  - eslint:recommended
  - react-app
  - prettier
env:
  browser: true
  node: true
parserOptions:
  ecmaVersion: latest
  sourceType: module
overrides:
  - files: ["*.astro"]
    parser: "astro-eslint-parser"
    parserOptions:
      parser: "@typescript-eslint/parser"
      extraFileExtensions: [".astro"]
